services:
  app:
    build: ./backend
    image: neuro-demo-app
    container_name: neuro-demo-app
    ports:
      - "9000:8000"
    environment:
      # 데이터/정적 경로 (컨테이너 내부 고정)
      - DATA_DIR=/app/data/precomputed
    volumes:
      - ./appdata:/app/data
    command: >
      sh -c "
      python generate_volume.py &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
