"""init schema

Revision ID: c0510303cf78
Revises: 
Create Date: 2025-10-14 23:59:30.791568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0510303cf78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('LoginId', sa.String(length=50), nullable=True),
    sa.Column('HashedPassword', sa.String(length=100), nullable=True),
    sa.Column('UserName', sa.String(length=50), nullable=True),
    sa.Column('Role', sa.String(length=20), nullable=True),
    sa.Column('UserImage', sa.String(length=255), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_users_Id'), 'users', ['Id'], unique=False)
    op.create_index(op.f('ix_users_LoginId'), 'users', ['LoginId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_LoginId'), table_name='users')
    op.drop_index(op.f('ix_users_Id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
