services:
  zarr_dzi_server:
    container_name: zarr-dzi-server
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./data:/app/data
      - ./cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=1   # 과한 스레딩 방지(서버 안정성)
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]